"""add s3 v0 column to video file table

Revision ID: 1abf979b12ea
Revises: 223e9cf5840c
Create Date: 2024-05-29 01:07:15.499005

"""

# revision identifiers, used by Alembic.
revision = '1abf979b12ea'
down_revision = '223e9cf5840c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_file', sa.Column('blob_storage_url_v0', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_file', 'blob_storage_url_v0')
    # ### end Alembic commands ###
