"""add keyframes informations in video_file table

Revision ID: 223e9cf5840c
Revises: e2262720fca7
Create Date: 2023-10-25 09:59:21.591064

"""

# revision identifiers, used by Alembic.
revision = '223e9cf5840c'
down_revision = 'e2262720fca7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_file', sa.Column('kf_tile_size', sa.Integer(), nullable=True))
    op.add_column('video_file', sa.Column('kf_frame_width', sa.Integer(), nullable=True))
    op.add_column('video_file', sa.Column('kf_frame_height', sa.Integer(), nullable=True))
    op.add_column('video_file', sa.Column('kf_image_path_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_file', 'kf_image_path')
    op.drop_column('video_file', 'kf_frame_height')
    op.drop_column('video_file', 'kf_frame_width')
    op.drop_column('video_file', 'kf_tile_size')
    # ### end Alembic commands ###
