"""convert video_file table column file_path, file_name, label type to TEXT

Revision ID: 478da9c6a57e
Revises: e2262720fca7
Create Date: 2022-03-12 04:07:03.747994

"""

# revision identifiers, used by Alembic.
revision = '478da9c6a57e'
down_revision = 'e2262720fca7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_file', column_name='file_name', type_=sa.TEXT)
    op.alter_column('video_file', column_name='file_path', type_=sa.TEXT)
    op.alter_column('video_file', column_name='label', type_=sa.TEXT)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_file', column_name='file_name', type_=sa.String)
    op.alter_column('video_file', column_name='file_path', type_=sa.String)
    op.alter_column('video_file', column_name='label', type_=sa.String)
    # ### end Alembic commands ###
